### PR TITLE
Add Example Project

### PR DESCRIPTION
**Pull request by bobbyg603**
* Adds an example project for verifying Angular 15 upgrade
* Moves existing library to projects folder to follow Angular conventions
* Updates build command to use ng

### CODE REVIEW

**Comment by bobbyg603** [comment]
hi @georgipeltekov, I created this project before I noticed you had already published something to your GitHub pages site. Perhaps we could start here, and you might integrate your existing example at a later date?

Also, you might consider [adding some tooling to deploy to GitHub pages and publish to npm](https://betterprogramming.pub/ci-cd-for-angular-developers-be9a1485d22b). If you're open to this, I would be willing to open another PR.

**Comment by georgipeltekov** [comment]
Yes sounds like a great idea, lets do this!

P.S: I will be on a business trip for the next few weeks and will have limited availability

**Comment by bobbyg603** [comment]
@georgipeltekov awesome! I'm traveling this week as well - no rush. I'll await a review and a merge on this PR, when we get this sorted, I'll have a go at the CI/CD pipeline.

**Comment by bobbyg603** [comment]
> Hey @bobbyg603 ,
> 
> on the second though... I don't feel much comfortable to add additional files to the library, just for having an example project, within the code of the library. Let just keep it as simple and small as possible ( less is much :) ). I think it is better to provide and external link in the Wiki to other repo, where people can check some example project and guidance. In this way we can achieve both targets: keeping the library small and simple and having easy accessible example project for reference. I dont even mind if this external repo is mine or not :) So we can use yours as well.
> 
> What are your thoughts on that?

We did this on our fork to reduce development friction. It's a bit awkward to develop a library and perform major version updates for Angular without an easy way to verify those changes. It's possible to use `npm link` here, but historically that approach has had lots of weird issues and gotchas. Another option is `npm build` with a copy to an example app which works but feels a bit cumbersome.

I guess I'd like to better understand your discomfort around this approach? At BugSplat we have a few libraries that we maintain and this approach has worked pretty well for us, but I realize YMMV.

**Comment by georgipeltekov** [comment]
Hey @bobbyg603 

the reason is to keep the library small and with less files, logic and dependencies as possible. I totally agree that having such demo project in the code helps , but it helps the developers, who want to improve the library. All the other users, who just want to use the library - they don't need that code, they only need a wiki, what to import and how to use it and a live demo page, where they can check ,what the library can do( no code needed). And unfortunately, the people who spent time on improving  this lib are extremely few, but who luckily have enough knowledge to workaround this downside. 

Does this make sense, what do you think about it?

P.S: man, thank you for the good discussion

**Comment by bobbyg603** [comment]
@georgipeltekov I'm not sure I follow. The sample does not get shipped with the library, instead it's just a tool that exists for developers that clone and work on the repo. There will be no extra code shipped to the end user via npm.

**Comment by bobbyg603** [comment]
> @georgipeltekov I'm not sure I follow. The sample does not get shipped with the library, instead it's just a tool that exists for developers that clone and work on the repo. There will be no extra code shipped to the end user via npm.
> 
> PS I'm thankful that you are so responsive! We've forked several Angular libraries because they have been abandoned by their maintainers 😔. I'm glad that you are still active!

To this point, you can actually see this in our published fork that none of the sample code is shipped, it is completely independent from the library. Here's a link to the [code that gets shipped via npm](https://www.npmjs.com/package/@bugsplat/ngx-file-drop?activeTab=explore).

**Comment by georgipeltekov** [comment]
@bobbyg603  Thank you very much for the clarification, in that case it makes sense to have this code as well. Will try to check it it until the end of next week ( travelling and the work schedule is quite tight)

**Comment by bobbyg603** [comment]
@georgipeltekov awesome! no rush here, let me know if there's anything i can do to help 🙂

**Comment by georgipeltekov** [comment]
I got eager and woke up early to check this. Thank you once again for the contribution

**Comment by bobbyg603** [comment]
@georgipeltekov awesome! thanks for merging, I'll be on the lookout for other features to move back upstream. When I have a bit more time, I'll send a PR for CI/CD updates  🙂

**Pull request merged**
