### PR TITLE
feat!: update to Angular 15

### PR DESCRIPTION
**Pull request by bobbyg603**
BREAKING CHANGE: Updates to Angular 15

### CODE REVIEW

**Comment by georgipeltekov** [comment]
Hey, 

first of all, thank you very much on your effort on supporting and updating this library. They are quite a lot of changes here, are they all necessary? I see repository changes, business logic changes, project structure changes, not only Angular 15 update. Maybe it is better idea to have separate merge requests for the different improvements?

**Comment by bobbyg603** [comment]
@georgipeltekov apologies, i didn't mean to open the PR in this repo, we have been maintaining our own fork and I was in the process of updating it to angular 15

**Comment by bobbyg603** [comment]
> @georgipeltekov apologies, i didn't mean to open the PR in this repo (I forgot forked repos can only open PRs back to upstream), we have been maintaining our own fork and I was in the process of updating it to angular 15

@georgipeltekov I could potentially backport some of these changes, with or without the business logic changes. I did manage to add a sample, and get everything updated to Angular 15. Looking at our fork, are there any specific changes you would like to see merged upstream?

Also, I believe the business logic changes were mostly about removing things that depended on deprecated APIs (which this library may or may not have already addressed).

Happy to contribute anything you think would be valuable 🙂

**Comment by georgipeltekov** [comment]
Hey @bobbyg603 , no worries :)

If you don`t mind I will be happy to see a clear Angular 15 merge request update. Frankly I have very limited time, but lets do our best to improve this library so all the folks out there could use it for free :)

Of course, any justificated business logic change is more than welcome ( but in separate MR)

**Comment by bobbyg603** [comment]
Hi @georgipeltekov, I've opened #280 which updates to Angular v15. I've also opened #281 which adds a sample to the project to demonstrate usage and test future version upgrades. Hope this helps 🙂

**Pull request closed without merging**
