### PR TITLE
Angular 10 support

### PR DESCRIPTION
**Pull request by 128keaton**
Test using my `release` branch:
```
  "ngx-file-drop": "128keaton/ngx-file-drop#release",
```

### CODE REVIEW

**Comment by georgipeltekov** [comment]
Hi,

thank you for your contribution! For some reason these changes are breaking the travis build:
https://travis-ci.com/github/128keaton/ngx-file-drop/builds/185874534

Also could you please update the changelog file?

**Comment by zaki785** [comment]
@georgipeltekov I have an issue using this 'ngx-file-drop' package.

In fact, when I want to drop a file coming from Outlook application, the email goes to the trash folder due to the property event.dataTransfer.effectAllowed not set to 'copy'.

There is an update that will fixed this issue ?

Thanks in advance

**Comment by 128keaton** [comment]
@georgipeltekov I'll take a look asap

**Comment by MitchellStrong** [comment]
Any update on the support of angular 10?

**Comment by 128keaton** [comment]
Ok, tests failed due to a linter problem. Was able to have it build successfully in my own Travis CI instance.
Screen Shot 2020-10-02 at 9 28 41 AM

**Pull request merged**
