### PR TITLE
Update build process & project structure for releasing npm package compatible with angular 4 +

### PR DESCRIPTION
**Pull request by maartenmensink**
Packages added or updated
 - ng-packagr 
 - typescript
 - angular cli

**ng-packagr**
I added ng-packagr according to [this description ](https://medium.com/@ngl817/building-an-angular-4-component-library-with-the-angular-cli-and-ng-packagr-53b2ade0701e) this package will handle all the packaging of the npm package.

Use the following commands to create a npm package

 run `npm run packagr` to generate a dist folder which can be packaged. 
 run `npm publish dist` to publish package based on the dist folder.

I have tested the release locally by create a package by running 

```
npm run packagr
cd dist
npm pack
```

and then in the depended project do a `npm install <path_to_tgz>` file 

I have also tested the package in npm build --prod and --aot 

I also ran `ng lint` and fixed most lint errors.

### CODE REVIEW

**Comment by maartenmensink** [comment]
@georgipeltekov i noticed that the travis.yml does a `npm build` instead of a `npm build --prod` prod is stricter so imo this would be a better choice to run in the build.

**Comment by georgipeltekov** [comment]
There are a lot of deletions and file removal in the merge request. What is the reason for that?

**Comment by maartenmensink** [comment]
@georgipeltekov hmm crap for some reason git decided not to add the src folder let me check the .gitignore file

**Comment by maartenmensink** [comment]
@georgipeltekov ah the .gitignore has /* to ignore everything new... maybe that is a bit to harsh. So that is why the src dir was ignored on the commit!

**Comment by maartenmensink** [comment]
Pull request updated! Good catch!

**Comment by georgipeltekov** [comment]
hmm, did you manage to run it locally. After getting your branch and try running npm install and after that ng serve I am getting:

ERROR in E:/prj/ngx-file-drop/ngx-file-drop/node_modules/rxjs/Subject.d.ts (16,22): Class 'Subject<T>' incorrectly extends base class 'Observable<T>'.
  Types of property 'lift' are incompatible.
    Type '<R>(operator: Operator<T, R>) => Observable<T>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<R>'.
      Type 'Observable<T>' is not assignable to type 'Observable<R>'.
        Type 'T' is not assignable to type 'R'.
ERROR in E:/prj/ngx-file-drop/ngx-file-drop/node_modules/rxjs/observable/dom/WebSocketSubject.d.ts (24,22): Class 'WebSocketSubject<T>' incorrectly extends base class 'AnonymousSubject<T>'.
  Types of property 'lift' are incompatible.
    Type '<R>(operator: Operator<T, R>) => WebSocketSubject<R>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<T>'.
      Type 'WebSocketSubject<R>' is not assignable to type 'Observable<T>'.
        Types of property 'operator' are incompatible.
          Type 'Operator<any, R>' is not assignable to type 'Operator<any, T>'.
            Type 'R' is not assignable to type 'T'.

**Comment by maartenmensink** [comment]
@georgipeltekov yes i have it running on my machine. Looks to me there is a version issue for on of the packages.

**Comment by maartenmensink** [comment]
Try deleting your node_modules folder and the package-lock.json file

I am running the following versions.

image

Which results in

image

**Comment by georgipeltekov** [comment]
yep I think this is the problem. you are running it under angular 5 and I under angular 4, which may be the cause of the issue. But anyway, this should not break the existing angular 4 compatibility

**Comment by maartenmensink** [comment]
@georgipeltekov 

I just downgraded the local version to 4.4.6

image

Both the ng build and ng serve gives me a proper build result.

**Comment by georgipeltekov** [comment]
the build seems to be fine now. It was on my side. The sandbox is working fine, however when I try to use the package in a separate application (wuth angular 4) I am not able to import it. I am attaching the result on npm pack, could you try to use it in a separate application? 
[ngx-file-drop-2.0.0.zip](https://github.com/georgipeltekov/ngx-file-drop/files/1487216/ngx-file-drop-2.0.0.zip)

**Comment by maartenmensink** [comment]
Dit you run the following command in succession on the latest? Because it seems the package that has been generated is invalid. 

```
npm run packagr
cd dist
npm pack
``` 

Because this is the result i get after running the commands.

[ngx-file-drop-1.0.18.zip](https://github.com/georgipeltekov/ngx-file-drop/files/1487246/ngx-file-drop-1.0.18.zip)

And that installs just fine

image

**Comment by georgipeltekov** [comment]
the master is fine, but it uses old version of building and packaging. If I run npm run on this branch packagr I am getting:

Error File 'E:/prj/ngx-file-drop/ngx-file-drop/.ng_pkg_build/ngx-file-drop/ts/public_api.ts' not found.
Error: Error File 'E:/prj/ngx-file-drop/ngx-file-drop/.ng_pkg_build/ngx-file-drop/ts/public_api.ts' not found.
    at UserError.Error (native)
    at new UserError (E:\prj\ngx-file-drop\ngx-file-drop\node_modules\@angular\tsc-wrapped\src\tsc.js:27:28)
    at Object.check (E:\prj\ngx-file-drop\ngx-file-drop\node_modules\@angular\tsc-wrapped\src\tsc.js:93:15)
    at Object.main (E:\prj\ngx-file-drop\ngx-file-drop\node_modules\@angular\tsc-wrapped\src\main.js:100:15)
    at Object.<anonymous> (E:\prj\ngx-file-drop\ngx-file-drop\node_modules\ng-packagr\lib\steps\ngc.js:42:29)
    at next (native)
    at fulfilled (E:\prj\ngx-file-drop\ngx-file-drop\node_modules\ng-packagr\lib\steps\ngc.js:4:58)

**Comment by maartenmensink** [comment]
Please do a get the latest source. Due to the setup of the .gitignore more needed files where ignored while i was checking in the code which created that mess :) sorry about that!

**Pull request merged**
