### PR TITLE
Add directory parameter

### PR DESCRIPTION
**Pull request by Saurye**

### CODE REVIEW

**Comment by Saurye** [comment]
@georgipeltekov fixed the regression issue and opened another PR

**Comment by georgipeltekov** [comment]
The regression seems to be fixed, good job! However there is problem with the default values of this attribute. The only way to accept files was to pass directory=null, both removing the parameter or setting directory=false ( both cases should be valid) didn't work

**Comment by Saurye** [comment]
@georgipeltekov You're right. Fixed it by putting "undefined" for every value that is "falsy".

**Comment by georgipeltekov** [comment]
I just published 8.0.8. Thank you for your contribution!

**Pull request merged**
